/*
 * Monedas
 * Servicio para la gestion de monedas
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Representa una moneda
 */
@ApiModel(description = "Representa una moneda")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-11T17:37:02.635-03:00")
public class Moneda {
  @SerializedName("cotizacion")
  private Double cotizacion = null;

  @SerializedName("descripcion")
  private String descripcion = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("simbolo")
  private String simbolo = null;

  public Moneda cotizacion(Double cotizacion) {
    this.cotizacion = cotizacion;
    return this;
  }

   /**
   * Get cotizacion
   * @return cotizacion
  **/
  @ApiModelProperty(value = "")
  public Double getCotizacion() {
    return cotizacion;
  }

  public void setCotizacion(Double cotizacion) {
    this.cotizacion = cotizacion;
  }

  public Moneda descripcion(String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

   /**
   * Get descripcion
   * @return descripcion
  **/
  @ApiModelProperty(value = "")
  public String getDescripcion() {
    return descripcion;
  }

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }

  public Moneda id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Moneda simbolo(String simbolo) {
    this.simbolo = simbolo;
    return this;
  }

   /**
   * Get simbolo
   * @return simbolo
  **/
  @ApiModelProperty(value = "")
  public String getSimbolo() {
    return simbolo;
  }

  public void setSimbolo(String simbolo) {
    this.simbolo = simbolo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Moneda moneda = (Moneda) o;
    return Objects.equals(this.cotizacion, moneda.cotizacion) &&
        Objects.equals(this.descripcion, moneda.descripcion) &&
        Objects.equals(this.id, moneda.id) &&
        Objects.equals(this.simbolo, moneda.simbolo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cotizacion, descripcion, id, simbolo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Moneda {\n");
    
    sb.append("    cotizacion: ").append(toIndentedString(cotizacion)).append("\n");
    sb.append("    descripcion: ").append(toIndentedString(descripcion)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    simbolo: ").append(toIndentedString(simbolo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

